name: viewer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+5

environment:
  sdk: ^3.6.1

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
