name: Build and Deploy Flutter Web to GitHub Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Increase Build Number"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build flutter web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web
          # git-config-name: github-actions
          # git-config-email: github-actions@github.com